version: '3.8'

services:
  php:
    container_name: php_dblib
    build:
      context: ./php
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../www:/var/www/html/
    depends_on:
      - sybase
    networks:
      - sybase-network

  sybase:
    container_name: sybase_16.0
    privileged: true
    image: datagrip/sybase:16.0
    ports:
      - "5000:5000"
    healthcheck:
      test: "exit 0"
    networks:
      - sybase-network

networks:
  sybase-network:

